/** Declaration file generated by dts-gen */
declare namespace __velocity {
    export class VelocityComponent extends React.Component<any,any>{
        constructor(props: any, context: any, updater: any);
        componentDidMount(): void;
        componentWillUnmount(): void;
        componentWillUpdate(newProps: any, newState: any): void;
        render(): any;
        runAnimation(config: any): void;
        static defaultProps: {
            animation: any;
            runOnMount: boolean;
            targetQuerySelector: any;
        };
        static displayName: string;
        static getDefaultProps(): any;
    }
    export class VelocityTransitionGroup extends React.Component<any,any>{
        constructor(props: any, context: any, updater: any);
        childWillAppear(node: any, doneFn: any): void;
        childWillEnter(node: any, doneFn: any): void;
        childWillLeave(node: any, doneFn: any): void;
        componentWillMount(): void;
        componentWillUnmount(): void;
        render(): any;
        static defaultProps: {
            enter: any;
            enterHideStyle: {
                display: string;
            };
            enterShowStyle: {
                display: string;
            };
            leave: any;
            runOnMount: boolean;
        };
        static disabledForTest: boolean;
        static displayName: string;
        static getDefaultProps(): any;
    }
    export namespace VelocityComponent {
        // namespace getDefaultProps {
        //     const isReactClassApproved: {
        //     };
        // }
        namespace propTypes {
            function animation(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function children(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function runOnMount(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function targetQuerySelector(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            namespace animation {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace runOnMount {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace targetQuerySelector {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
        }
    }
    export namespace VelocityTransitionGroup {
        // namespace getDefaultProps {
        //     const isReactClassApproved: {
        //     };
        // }
        namespace propTypes {
            function children(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function enter(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function enterHideStyle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function enterShowStyle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function leave(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            function runOnMount(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            namespace children {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace enter {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace enterHideStyle {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace enterShowStyle {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace leave {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
            namespace runOnMount {
                function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
            }
        }
    }
    export namespace velocityHelpers {
        function registerEffect(suffix: any, animation: any): any;
    }

}

declare module "velocity-react" {
    export = __velocity
}